language: swift
osx_image: xcode9.2
xcode_project: StellarKit.xcodeproj
xcode_scheme: StellarKit
xcode_sdk: iphonesimulator8.4

before_script:
  #Install appium
  - brew install python3
  - brew install node
  - npm install -g appium
  - npm install -g wd
  - sudo pip3 install --trusted-host pypi.python.org  Appium-Python-Client pytest requests
  - appium &
  - git clone https://github.com/kinfoundation/Kin-Stellar-SampleApp-Automation.git
script:
  - cd KinSDK
  - xcodebuild test -scheme KinSDK -destination 'platform=iOS Simulator,name=iPhone 8 Plus'
#Build sample app
  - cd ..
  - cd KinSampleApp
  - xcodebuild -scheme KinSampleApp -destination 'platform=iOS Simulator,name=iPhone 8 Plus'
