language: swift
osx_image: xcode9.1

cache:
  directories:
    - node_modules

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install 8.9.1
  - node --version
  - npm install

script:
  - make test
  
after_script:
  - cat truffle.log
  - cat testrpc.log
